project_name: 'LSTM_cifar10'
run_id: '1_resume'
use_wandb: True
record: True
wandb_entity: 'tjproject'
resume: True

gpu_id: 0
num_workers: 4
num_epochs: 1500
train_batch_size: 128
test_batch_size: 128
dataset: 'cifar10'
data_path: '/data/dataSets/cifar10'
input_size: '32x32'

model: 'lstm'      #使用的網路模型
img_size: 32
hidden_size: 128
num_layers: 5
output_size: 10

optimizer_type: 'SGD'
learning_rate: 0.001
weight_decay: 0.0001        # 0 means not using weight decay
momentum: 0.9               # 0 means not using momentum
lr_scheduler: 'none'
# sche_step: 30
# gamma: 0.1

# update_freq: 1            #backward頻率
log_freq: 64                #上傳頻率
ckp_epochs: 20              #save checkpoint every _ epochs
